{ lib, config, ... }:
let
  cfg = config.ssh.allowedSigners;
in
{
  options.ssh.allowedSigners = lib.mkOption {
    type = lib.types.listOf (
      lib.types.submodule {
        options = {
          email = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Signer principal. Null reads user.email from emailConfigFile at activation.";
          };
          emailConfigFile = lib.mkOption {
            type = lib.types.str;
            default = "${config.home.homeDirectory}/.gitconfig.local";
            description = "Local Git config file used to read the signer principal when email is null.";
          };
          keyFile = lib.mkOption { type = lib.types.str; };
        };
      }
    );
    default = [ ];
    description = "SSH signing key entries written to ~/.ssh/allowed_signers on every activation.";
  };

  config = lib.mkIf (cfg != [ ]) {
    home.activation.updateAllowedSigners = lib.hm.dag.entryAfter [ "writeBoundary" ] (
      let
        git = lib.getExe config.programs.git.package;
        entries = lib.concatMapStrings (e: ''
          _email=${
            if e.email != null then
              lib.escapeShellArg e.email
            else
              ''"$(${git} config --file ${lib.escapeShellArg e.emailConfigFile} user.email 2>/dev/null || true)"''
          }
          if [[ -z "$_email" ]]; then
            verboseEcho "allowed_signers: no user.email in ${e.emailConfigFile}; skipping ${e.keyFile}"
          elif [[ -f "${e.keyFile}" ]]; then
            read -r _ktype _kpub _ < "${e.keyFile}"
            echo "$_email $_ktype $_kpub" >> "$_signers_tmp"
          else
            verboseEcho "allowed_signers: ${e.keyFile} not found; skipping $_email"
          fi
        '') cfg;
      in
      ''
        verboseEcho "updating $HOME/.ssh/allowed_signers"
        run install -d -m 700 "$HOME/.ssh"
        _signers_tmp="$(mktemp)"
        printf '%s\n' '# Generated by Home Manager; do not edit.' > "$_signers_tmp"
        ${entries}
        run install -m 644 "$_signers_tmp" "$HOME/.ssh/allowed_signers"
        run rm -f "$_signers_tmp"
        unset _email _ktype _kpub _signers_tmp
      ''
    );
  };
}
