{
  config,
  lib,
  pkgs,
  ...
}:
let
  dotfilesPath = config.dotfiles.path;
  tmuxPath = lib.concatStringsSep ":" (
    (map (dir: "#{E:HOME}/${dir}") config.dotfiles.env.userBinDirs)
    ++ [
      "#{E:HOME}/${config.dotfiles.env.nixProfileBinDir}"
      "/etc/profiles/per-user/#{E:USER}/bin"
      "/run/current-system/sw/bin"
      "/nix/var/nix/profiles/default/bin"
    ]
    ++ lib.optionals pkgs.stdenv.hostPlatform.isDarwin config.dotfiles.env.darwinPackageBinDirs
    ++ config.dotfiles.env.systemBinDirs
  );

  tmuxEnvironment = ''
    # tmux environment - generated by Home Manager.
    set-environment -gF PATH "${tmuxPath}"
    set-environment -gF TMUX_PLUGIN_MANAGER_PATH "#{E:HOME}/.config/tmux/plugins/"
  '';

in
{
  # Prevent tmux-fzf-url from downloading xre into user state on first use.
  home.packages = [ pkgs.xre ];

  xdg.configFile = {
    "tmux/tmux.conf".source =
      config.lib.file.mkOutOfStoreSymlink "${dotfilesPath}/config/tmux/tmux.conf";
    "tmux/environment.conf".text = tmuxEnvironment;
  };

  home.activation.bootstrapTpm = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    export PATH="${
      lib.makeBinPath [
        pkgs.bash
        pkgs.coreutils
        pkgs.gawk
        pkgs.git
        pkgs.gnused
        pkgs.tmux
      ]
    }:$PATH"

    tpm_dir="$HOME/.config/tmux/plugins/tpm"

    if [[ ! -d "$tpm_dir/.git" ]]; then
      if [[ -x "${pkgs.git}/bin/git" ]]; then
        run mkdir -p "$HOME/.config/tmux/plugins"
        run ${pkgs.git}/bin/git clone --depth 1 https://github.com/tmux-plugins/tpm "$tpm_dir" || \
          echo "tmux: failed to clone TPM; open tmux and install manually from https://github.com/tmux-plugins/tpm" >&2
      else
        echo "tmux: git missing; cannot bootstrap TPM" >&2
      fi
    fi

    if [[ -x "$tpm_dir/bin/install_plugins" ]]; then
      tmux_term="''${TERM:-}"
      if [[ -z "$tmux_term" || "$tmux_term" == "unknown" || "$tmux_term" == "dumb" ]]; then
        tmux_term="screen-256color"
      fi

      previous_term_set=0
      previous_term=""
      if [[ -v TERM ]]; then
        previous_term_set=1
        previous_term="$TERM"
      fi
      export TERM="$tmux_term"

      if run ${pkgs.tmux}/bin/tmux start-server \; set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins/"; then
        run "$tpm_dir/bin/install_plugins" || \
          echo "tmux: TPM plugin install failed; run prefix + I inside tmux" >&2
        if [[ -x "$tpm_dir/bin/clean_plugins" ]]; then
          run "$tpm_dir/bin/clean_plugins" || \
            echo "tmux: TPM plugin cleanup failed; run prefix + alt-u inside tmux" >&2
        fi

        # TPM's substring match mistakes tmux-fzf for the retained tmux-fzf-url.
        if [[ -d "$HOME/.config/tmux/plugins/tmux-fzf" ]]; then
          run rm -rf "$HOME/.config/tmux/plugins/tmux-fzf" || \
            echo "tmux: failed to remove the retired tmux-fzf plugin" >&2
        fi
      else
        echo "tmux: skipping TPM plugin install during activation; run prefix + I inside tmux" >&2
      fi

      if [[ "$previous_term_set" -eq 1 ]]; then
        export TERM="$previous_term"
      else
        unset TERM
      fi
    fi
  '';
}
